-- Migration: Add Serenian II, III, IV worlds
-- The application handles worlds primarily via the WORLDS constant in utils/constants.ts
-- and through data file parsing. There is no explicit 'worlds' table with constraints.
-- World names are stored as plain strings in kill_history, characters, etc.
--
-- This migration is documentation for the new worlds added:
--   - Serenian II  (Optional PVP, select value: 23)
--   - Serenian III (Optional PVP, select value: 24)
--   - Serenian IV  (Optional PVP, select value: 25)
--
-- All Serenian variants use the same PvP type icon (optional-pvp.gif).
-- No database schema changes are required — the new worlds are recognized
-- by adding them to the WORLDS array in utils/constants.ts.
--
-- If a 'worlds' table is created in the future, run:
-- INSERT INTO worlds (name, type) VALUES
--   ('Serenian II', 'Optional PVP'),
--   ('Serenian III', 'Optional PVP'),
--   ('Serenian IV', 'Optional PVP')
-- ON CONFLICT DO NOTHING;
