export const bossImages: Record<string, string> = {
  "Alptramun": "https://www.tibiawiki.com.br/images/c/c9/Alptramun.gif",
  "Anmothra": "https://www.tibiawiki.com.br/images/d/d2/Anmothra.gif",
  "Arachir the Ancient One": "https://www.tibiawiki.com.br/images/c/c3/Arachir_the_Ancient_One.gif",
  "Arthom the Hunter": "https://www.tibiawiki.com.br/images/9/95/Arthom_the_Hunter.gif",
  "Bakragore": "https://www.tibiawiki.com.br/images/5/55/Bakragore.gif",
  "Bane Lord": "https://www.tibiawiki.com.br/images/6/6e/Bane_Lord.gif",
  "Barbaria": "https://www.tibiawiki.com.br/images/8/88/Barbaria.gif",
  "Battlemaster Zunzu": "https://www.tibiawiki.com.br/images/1/1d/Battlemaster_Zunzu.gif",
  "Big Boss Trolliver": "https://www.tibiawiki.com.br/images/3/3f/Big_Boss_Trolliver.gif",
  "Burster": "https://www.tibiawiki.com.br/images/6/6f/Burster.gif",
  "Captain Jones": "https://www.tibiawiki.com.br/images/5/54/Captain_Jones.gif",
  "Chikhaton": "https://www.tibiawiki.com.br/images/a/aa/Chikhaton.gif",
  "Chizzoron the Distorter": "https://www.tibiawiki.com.br/images/f/fa/Chizzoron_the_Distorter.gif",
  "Countess Sorrow": "https://www.tibiawiki.com.br/images/1/16/Countess_Sorrow.gif",
  "Cublarc the Plunderer": "https://www.tibiawiki.com.br/images/5/53/Cublarc_the_Plunderer.gif",
  "Devovorga": "https://www.tibiawiki.com.br/images/4/40/Devovorga.gif",
  "Dharalion": "https://www.tibiawiki.com.br/images/e/ed/Dharalion.gif",
  "Draptor": "https://www.tibiawiki.com.br/images/1/1b/Draptor.gif",
  "Crustacea Gigantica": "https://www.tibiawiki.com.br/images/5/52/Crustacea_Gigantica.gif",
  "Diblis the Fair": "https://www.tibiawiki.com.br/images/0/0f/Diblis_the_Fair.gif",
  "Dracola": "https://www.tibiawiki.com.br/images/5/53/Dracola.gif",
  "Dreadful Disruptor": "https://www.tibiawiki.com.br/images/0/09/Dreadful_Disruptor.gif",
  "Dreadmaw": "https://www.tibiawiki.com.br/images/7/7f/Dreadmaw.gif",
  "Munster": "https://www.tibiawiki.com.br/images/a/aa/Munster.gif",
  "Elvira Hammerthrust": "https://www.tibiawiki.com.br/images/f/fa/Elvira_Hammerthrust.gif",
  "Feroxa (Mortal)": "https://www.tibiawiki.com.br/images/e/ec/Feroxa_%28Mortal%29.gif",
  "Ferumbras": "https://www.tibiawiki.com.br/images/0/0f/Ferumbras.gif",
  "Ferumbras Mortal Shell": "https://www.tibiawiki.com.br/images/f/f1/Ferumbras_Mortal_Shell.gif",
  "Flamecaller Zazrak": "https://www.tibiawiki.com.br/images/8/8d/Flamecaller_Zazrak.gif",
  "Fleabringer": "https://www.tibiawiki.com.br/images/1/1c/Fleabringer.gif",
  "Foreman Kneebiter": "https://www.tibiawiki.com.br/images/4/46/Foreman_Kneebiter.gif",
  "Furyosa": "https://www.tibiawiki.com.br/images/e/e1/Furyosa.gif",
  "Gaz'Haragoth": "https://www.tibiawiki.com.br/images/6/63/Gaz%27Haragoth.gif",
  "General Murius": "https://www.tibiawiki.com.br/images/0/0b/General_Murius.gif",
  "Ghazbaran": "https://www.tibiawiki.com.br/images/5/5e/Ghazbaran.gif",
  "Goshnar's Megalomania": "https://www.tibiawiki.com.br/images/c/ce/Goshnar%27s_Megalomania.gif",
  "Grand Mother Foulscale": "https://www.tibiawiki.com.br/images/8/8e/Grand_Mother_Foulscale.gif",
  "Grandfather Tridian": "https://www.tibiawiki.com.br/images/b/b4/Grandfather_Tridian.gif",
  "Gravelord Oshuran": "https://www.tibiawiki.com.br/images/7/75/Gravelord_Oshuran.gif",
  "Groam": "https://www.tibiawiki.com.br/images/e/e0/Groam.gif",
  "Grorlam": "https://www.tibiawiki.com.br/images/9/92/Grorlam.gif",
  "Hairman The Huge": "https://www.tibiawiki.com.br/images/8/8a/Hairman_The_Huge.gif",
  "Hatebreeder": "https://www.tibiawiki.com.br/images/3/33/Hatebreeder.gif",
  "High Templar Cobrass": "https://www.tibiawiki.com.br/images/1/1f/High_Templar_Cobrass.gif",
  "Hirintror": "https://www.tibiawiki.com.br/images/9/93/Hirintror.gif",
  "Horestis": "https://www.tibiawiki.com.br/images/c/c3/Horestis.gif",
  "Irahsae": "https://www.tibiawiki.com.br/images/5/55/Irahsae.gif",
  "Izcandar Champion of Summer": "https://www.tibiawiki.com.br/images/c/c3/Izcandar_Champion_of_Summer.gif",
  "Izcandar Champion of Winter": "https://www.tibiawiki.com.br/images/5/53/Izcandar_Champion_of_Winter.gif",
  "Izcandar the Banished": "https://www.tibiawiki.com.br/images/0/0f/Izcandar_the_Banished.gif",
  "Jesse the Wicked": "https://www.tibiawiki.com.br/images/c/c6/Jesse_the_Wicked.gif",
  "King Chuck": "https://www.tibiawiki.com.br/images/2/2d/King_Chuck.gif",
  "Lizard Gate Guardian": "https://www.tibiawiki.com.br/images/e/e2/Lizard_Gate_Guardian.gif",
  "Mahatheb": "https://www.tibiawiki.com.br/images/0/0a/Mahatheb.gif",
  "Malofur Mangrinder": "https://www.tibiawiki.com.br/images/3/3b/Malofur_Mangrinder.gif",
  "Man In The Cave": "https://www.tibiawiki.com.br/images/9/93/Man_In_The_Cave.gif",
  "Massacre": "https://www.tibiawiki.com.br/images/9/9d/Massacre.gif",
  "Maxxenius": "https://www.tibiawiki.com.br/images/4/4c/Maxxenius.gif",
  "Morgaroth": "https://www.tibiawiki.com.br/images/c/ce/Morgaroth.gif",
  "Mornenion": "https://www.tibiawiki.com.br/images/8/84/Mornenion.gif",
  "Morshabaal": "https://www.tibiawiki.com.br/images/c/ca/Morshabaal.gif",
  "Mr. Punish": "https://www.tibiawiki.com.br/images/3/3f/Mr._Punish.gif",
  "Ocyakao": "https://www.tibiawiki.com.br/images/8/85/Ocyakao.gif",
  "Omrafir": "https://www.tibiawiki.com.br/images/e/e5/Omrafir.gif",
  "Oodok Witchmaster": "https://www.tibiawiki.com.br/images/8/8c/Oodok_Witchmaster.gif",
  "Orshabaal": "https://www.tibiawiki.com.br/images/c/ce/Orshabaal.gif",
  "Phrodomo": "https://www.tibiawiki.com.br/images/c/cc/Phrodomo.gif",
  "Plagueroot": "https://www.tibiawiki.com.br/images/2/24/Plagueroot.gif",
  "Raxias": "https://www.tibiawiki.com.br/images/1/15/Raxias.gif",
  "Robby the Reckless": "https://www.tibiawiki.com.br/images/d/d7/Robby_the_Reckless.gif",
  "Rotrender": "https://www.tibiawiki.com.br/images/3/38/Rotrender.gif",
  "Rotworm Queen": "https://www.tibiawiki.com.br/images/b/be/Rotworm_Queen.gif",
  "Rukor Zad": "https://www.tibiawiki.com.br/images/0/03/Rukor_Zad.gif",
  "Shlorg": "https://www.tibiawiki.com.br/images/f/f2/Shlorg.gif",
  "Sir Leopold": "https://www.tibiawiki.com.br/images/f/f6/Sir_Leopold.gif",
  "Sir Valorcrest": "https://www.tibiawiki.com.br/images/3/32/Sir_Valorcrest.gif",
  "Smuggler Baron Silvertoe": "https://www.tibiawiki.com.br/images/d/da/Smuggler_Baron_Silvertoe.gif",
  "Teneshpar": "https://www.tibiawiki.com.br/images/9/96/Teneshpar.gif",
  "The Abomination": "https://www.tibiawiki.com.br/images/a/a7/The_Abomination.gif",
  "The Big Bad One": "https://www.tibiawiki.com.br/images/a/a1/The_Big_Bad_One.gif",
  "The Blightfather": "https://www.tibiawiki.com.br/images/0/02/The_Blightfather.gif",
  "The Evil Eye": "https://www.tibiawiki.com.br/images/9/93/The_Evil_Eye.gif",
  "The First Dragon (Criatura)": "https://www.tibiawiki.com.br/images/b/bf/The_First_Dragon_%28Criatura%29.gif",
  "The Frog Prince": "https://www.tibiawiki.com.br/images/d/d0/The_Frog_Prince.gif",
  "The Handmaiden": "https://www.tibiawiki.com.br/images/7/73/The_Handmaiden.gif",
  "The Hungerer": "https://www.tibiawiki.com.br/images/c/ce/The_Hungerer.gif",
  "The Imperor": "https://www.tibiawiki.com.br/images/b/b3/The_Imperor.gif",
  "The Last Lore Keeper": "https://www.tibiawiki.com.br/images/3/33/The_Last_Lore_Keeper.gif",
  "The Manhunter": "https://www.tibiawiki.com.br/images/3/36/The_Manhunter.gif",
  "The Mean Masher": "https://www.tibiawiki.com.br/images/1/16/The_Mean_Masher.gif",
  "The Mutated Pumpkin": "https://www.tibiawiki.com.br/images/7/7b/The_Mutated_Pumpkin.gif",
  "The Old Whopper": "https://www.tibiawiki.com.br/images/c/c6/The_Old_Whopper.gif",
  "The Pale Count": "https://www.tibiawiki.com.br/images/1/11/The_Pale_Count.gif",
  "The Percht Queen": "https://www.tibiawiki.com.br/images/7/71/The_Percht_Queen.gif",
  "The Plasmother": "https://www.tibiawiki.com.br/images/9/98/The_Plasmother.gif",
  "The Voice of Ruin": "https://www.tibiawiki.com.br/images/8/8b/The_Voice_of_Ruin.gif",
  "The Welter": "https://www.tibiawiki.com.br/images/a/a3/The_Welter.gif",
  "Tyrn": "https://www.tibiawiki.com.br/images/7/7c/Tyrn.gif",
  "Tzumrah the Dazzler": "https://www.tibiawiki.com.br/images/5/51/Tzumrah_the_Dazzler.gif",
  "Warlord Ruzad": "https://www.tibiawiki.com.br/images/4/4f/Warlord_Ruzad.gif",
  "White Pale": "https://www.tibiawiki.com.br/images/a/ab/White_Pale.gif",
  "Willi Wasp": "https://www.tibiawiki.com.br/images/f/f1/Willi_Wasp.gif",
  "World Devourer": "https://www.tibiawiki.com.br/images/a/a8/World_Devourer.gif",
  "Xenia": "https://www.tibiawiki.com.br/images/1/1f/Xenia.gif",
  "Yaga the Crone": "https://www.tibiawiki.com.br/images/2/25/Yaga_the_Crone.gif",
  "Yakchal": "https://www.tibiawiki.com.br/images/4/41/Yakchal.gif",
  "Zarabustor": "https://www.tibiawiki.com.br/images/b/b0/Zarabustor.gif",
  "Zevelon Duskbringer": "https://www.tibiawiki.com.br/images/1/15/Zevelon_Duskbringer.gif",
  "Zomba": "https://www.tibiawiki.com.br/images/b/bb/Zomba.gif",
  "Zulazza the Corruptor": "https://www.tibiawiki.com.br/images/b/ba/Zulazza_the_Corruptor.gif",
  "Yeti": "https://www.tibiawiki.com.br/images/e/e9/Yeti.gif",
  "Midnight Panther": "https://www.tibiawiki.com.br/images/1/15/Midnight_Panther.gif",
  "Albino Dragon": "https://www.tibiawiki.com.br/images/0/06/Albino_Dragon.gif",
  "Zushuka": "https://www.tibiawiki.com.br/images/b/b5/Zushuka.gif",
  "Feroxa": "https://www.tibiawiki.com.br/images/2/2a/Feroxa_%28Imune%29.gif",
  "Maw": "https://www.tibiawiki.com.br/images/c/cb/Maw.gif",
  "Mindmasher": "https://www.tibiawiki.com.br/images/c/c6/Mindmasher.gif",
  "Rotspit": "https://www.tibiawiki.com.br/images/5/59/Rotspit.gif",
  "Chopper": "https://www.tibiawiki.com.br/images/8/8a/Chopper.gif",
  "Fernfang": "https://www.tibiawiki.com.br/images/6/64/Fernfang.gif",
  "Shadowstalker": "https://www.tibiawiki.com.br/images/2/2f/Shadowstalker.gif",
  "Teleskor": "https://www.tibiawiki.com.br/images/6/6c/Teleskor.gif",
  "Undead Cavebear": "https://www.tibiawiki.com.br/images/4/4b/Undead_Cavebear.gif",
  "Rottie the Rotworm": "https://www.tibiawiki.com.br/images/9/9a/Rottie_the_Rotworm.gif",
  "Apprentice Sheng": "https://www.tibiawiki.com.br/images/d/d5/Apprentice_Sheng.gif",
  "Frostreaper": "https://wiki.rubinot.com/annual-events/christmas-2025/bosses/frostreaper.png",
  "Frostbell": "https://wiki.rubinot.com/annual-events/christmas-2025/bosses/frostbell.apng",
  "Dire Penguin": "https://www.tibiawiki.com.br/images/d/d5/Dire_Penguin.gif",
};

export function getBossImage(bossName: string): string | null {
  // Try exact match first
  if (bossImages[bossName]) {
    return bossImages[bossName];
  }

  // Try case-insensitive match
  const lowercaseName = bossName.toLowerCase();
  const matchedKey = Object.keys(bossImages).find(
    key => key.toLowerCase() === lowercaseName
  );

  return matchedKey ? bossImages[matchedKey] : null;
}
